name: App workflow
on:
  push:
    branches:
      - 'main'
jobs:
  dockerize_production:
    name: Dockerize production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - id: vars
        run: echo "::set-output name=image_tag::production-$(git rev-parse --short HEAD)"

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: adn97/news-feed-app:${{ steps.vars.outputs.image_tag }},adn97/news-feed-app:latest
          build-args: ENV=production

      - run: echo ${{ steps.docker_build.outputs.digest }}

  deploy_production:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [dockerize_production]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - id: vars
        run: echo "::set-output name=image_tag::production-$(git rev-parse --short HEAD)"

      - uses: appleboy/scp-action@master
        with:
          host: 209.97.168.123
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: docker-compose.yml
          target: /root/flutter-news-feed-app/

      - uses: appleboy/ssh-action@master
        with:
          host: 209.97.168.123
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: export image_tag=${{ steps.vars.outputs.image_tag }} && cd /root/flutter-news-feed-app/ && docker-compose up -d
